### ISSUE TITLE
openimages_dataset_test is missing

### ISSUE THREAD

**Issue by MaxLeung99** [shlokk/object-cropping-ssl#1]
openimages_dataset_test is imported in main_lincls.py. However, openimages_dataset_test is missing.

**Comment by MaxLeung99** [comment]
Also, I wonder for validation, do you use test_40k? It seems that it has 500+ classes.

**Comment by shlokk** [comment]
Thanks for reaching out. I have added the code for testing on the OHMS dataset.
I was cleaning the code a month ago, and by mistake testing file got deleted; apologies for the delay.

Yes, even though we only take images from 208 classes, there are still some instances of other classes present. So, the primary classes are classes from selected 208 classes, but some images have objects from other classes which we have not removed. This, in general, makes the task actually a bit harder, which was a design choice we took while creating the OHMS dataset.
